[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "klippy_tmc_autotune"
readme = "README.md"
license = { text = "GPL3" }
version = "0.0.1"

[tool.setuptools.package-data]
klippy_tmc_autotune = [ "*.cfg" ]
